[project]
name = "reproducible-builds-rattler-build"
version = "0.1.0"
description = "Add a short description here"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[tasks]
build_recipes = "python generate_chart_data.py"
plot_data = "python plot.py"

[dependencies]
python = "~=3.10"
matplotlib = "*"
rattler-build = "*"
