name: Track how repro we are

on:
  push:
    branches:
      - main
  
  pull_request:
  workflow_dispatch:
      

jobs:
  build-recipes-ubunutu-22-04:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y pkg-config libssl-dev
      
      # - name: Set OpenSSL environment variables
      #   run: |
      #     echo "OPENSSL_DIR=/usr/lib/ssl" >> $GITHUB_ENV
      #     echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV
      #     echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Build recipes and track if hash is equal
        run: |
          pixi run python src/repror/build_recipe.py ubuntu 22.04
      
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/


  build-recipes-macos-13:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Build recipes and track if hash is equal
        run: |
          pixi run python src/repror/build_recipe.py macos 13

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/

  rebuild-recipes-ubuntu-20-04:
    runs-on: ubuntu-20.04
    needs: build-recipes-ubunutu-22-04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
      
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .

      - name: Rebuild recipes and track if hash is equal
        run: |
          # sudo apt-get install libssl-dev
          pixi run python src/repror/rebuild_recipe.py ubuntu 22.04 20.04
      
      - name: Upload diffoscope
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/ubuntu
            diffoscope_output/
            ci_artifacts/

            
  
  rebuild-recipes-macos-12:
    runs-on: macos-12
    needs: build-recipes-macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
      
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: .

      - name: Rebuild recipes and track if hash is equal
        run: |
          pixi run python src/repror/rebuild_recipe.py macos 13 12
      
      - name: Upload build info
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/macos
            diffoscope_output/
            ci_artifacts/

  statistics:
    runs-on: ubuntu-latest
    needs: [rebuild-recipes-ubuntu-20-04, rebuild-recipes-macos-12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
      
      - uses: actions/download-artifact@v3
        with:
          name: build-info
          path: .
      
      - run: | 
          ls -la build_info/
          ls -la build_info/ubuntu

      - name: Calculate statistics
        run: |
          pixi run python src/repror/statistics.py ubuntu_22.04_20.04 macos_13_12

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/history.json
          git add data/chart.png
          git add README.md
          git commit -m "Update file via GitHub Action"
          git push

      