name: Track how repro we are

on:
  push:
    branches:
      - main
  
  pull_request:
  workflow_dispatch:
      

jobs:
  build-recipes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Build recipes and track if hash is equal
        run: |
          mkdir /opt/bld
          pixi run python src/repror/build_recipe.py
      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            build_info/
            artifacts/

  rebuild-recipes:
    runs-on: macos-latest
    needs: build-recipes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
      
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: .

      - name: Rebuild recipes and track if hash is equal
        run: |
          sudo mkdir -p /opt/bld/rebuild_outputs
          sudo chmod -R 755 /opt/bld/
          pixi run python src/repror/rebuild_recipe.py
